dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.5.0
    # - OpenZeppelin/openzeppelin/contracts/token/ERC20/ERC20.sol

compiler:
    solc:
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"

networks:
    default: development
    mainnet-fork:
        eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    rinkeby:
        eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"

dotenv: .env
wallets:
    from_key: ${PRIVATE_KEY}
