dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.5.0

compiler:
    solc:
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"

dotenv: .env
wallets:
    from_key: ${HOT_WALLET}
